/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109131-g3e6816514c-20221118"
#endif /* AVUTIL_FFVERSION_H */
