#version 450

layout (local_size_x=32,local_size_y=32,local_size_z=1) in;

layout(binding = 0, rgba8) readonly uniform image2D source;

layout(binding = 1, rgba8) writeonly uniform image2D dest;

layout(binding = 2) readonly uniform options {
	float contrast;
	float pivot;
}

void main() {
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

	if (all(lessThan(pixel, imageSize(source)))) {
		imageStore(dest, pixel, vec4(0, 0, 0, 1));
	}
}